spring.application.name=producer-simulator1

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

# Device ID (to be set )
device.id=9aaf95b3-ea49-4cbd-8020-5064b16825e6

# CSV file path
sensor.csv.path=sensor.csv

